# Generated by Django 3.0.3 on 2021-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20210302_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=200, verbose_name='email'),
            preserve_default=False,
        ),
    ]
